#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: postgres-pv-volume  # Sets PV's name
#  labels:
#    type: local  # Sets PV's type to local
#    app: postgres
#spec:
##  storageClassName: ssd-postgres
#  capacity:
#    storage: 5Gi # Sets PV Volume
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data"
#---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  # Sets name of PVC
  labels:
    app: postgres
spec:
  storageClassName: ssd-postgres-rwo
  accessModes:
    - ReadWriteOnce  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size